config/routes.rb
Rails.application.routes.draw do
  resources :invites

  resources :pings

  resources :relationships

  resources :comments

  resources :activities

  resources :conversations

  resources :interests

  resources :users

  
  root :to => 'comments#index'

end

app/models/ping.rb
class Ping < ActiveRecord::Base
end

app/controllers/pings_controller.rb
class PingsController < ApplicationController
  before_action :set_ping, only: [:show, :edit, :update, :destroy]

  # GET /pings
  # GET /pings.json
  def index
    @pings = Ping.all
  end

  # GET /pings/1
  # GET /pings/1.json
  def show
  end

  # GET /pings/new
  def new
    @ping = Ping.new
  end

  # GET /pings/1/edit
  def edit
  end

  # POST /pings
  # POST /pings.json
  def create
    @ping = Ping.new(ping_params)

    respond_to do |format|
      if @ping.save
        format.html { redirect_to @ping, notice: 'Ping was successfully created.' }
        format.json { render :show, status: :created, location: @ping }
      else
        format.html { render :new }
        format.json { render json: @ping.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pings/1
  # PATCH/PUT /pings/1.json
  def update
    respond_to do |format|
      if @ping.update(ping_params)
        format.html { redirect_to @ping, notice: 'Ping was successfully updated.' }
        format.json { render :show, status: :ok, location: @ping }
      else
        format.html { render :edit }
        format.json { render json: @ping.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pings/1
  # DELETE /pings/1.json
  def destroy
    @ping.destroy
    respond_to do |format|
      format.html { redirect_to pings_url, notice: 'Ping was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ping
      @ping = Ping.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ping_params
      params.require(:ping).permit(:content, :sender_id, :conversation_id)
    end
end

app/helpers/pings_helper.rb
module PingsHelper
end

app/views/pings/_form.html.erb
<%= form_for(@ping) do |f| %>
  <% if @ping.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ping.errors.count, "error") %> prohibited this ping from being saved:</h2>

      <ul>
      <% @ping.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :sender_id %><br>
    <%= f.number_field :sender_id %>
  </div>
  <div class="field">
    <%= f.label :conversation_id %><br>
    <%= f.number_field :conversation_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pings/edit.html.erb
<h1>Editing ping</h1>

<%= render 'form' %>

<%= link_to 'Show', @ping %> |
<%= link_to 'Back', pings_path %>

app/views/pings/index.html.erb
<h1>Listing pings</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Sender</th>
      <th>Conversation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pings.each do |ping| %>
      <tr>
        <td><%= ping.content %></td>
        <td><%= ping.sender_id %></td>
        <td><%= ping.conversation_id %></td>
        <td><%= link_to 'Show', ping %></td>
        <td><%= link_to 'Edit', edit_ping_path(ping) %></td>
        <td><%= link_to 'Destroy', ping, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ping', new_ping_path %>

app/views/pings/new.html.erb
<h1>New ping</h1>

<%= render 'form' %>

<%= link_to 'Back', pings_path %>

app/views/pings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @ping.content %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @ping.sender_id %>
</p>

<p>
  <strong>Conversation:</strong>
  <%= @ping.conversation_id %>
</p>

<%= link_to 'Edit', edit_ping_path(@ping) %> |
<%= link_to 'Back', pings_path %>